name: regex_pattern_text_field
description: A custom text editing controller that applies styles to matched patterns in a text field.
version: 1.1.0
homepage: https://github.com/pablostefan/regex_pattern_text_field
repository: https://github.com/pablostefan/regex_pattern_text_field
issue_tracker: https://github.com/pablostefan/regex_pattern_text_field/issues

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
